config/routes.rb
Rails.application.routes.draw do
  resources :mini_blogs do
    resources :comments
  end
  resources :users
  root "application#hi"
  get "secret/" => "application#secret"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :mini_blog
  validates :text, length: { minimum: 1 },
                   length: { maximum: 140 }
end

app/models/mini_blog.rb
class MiniBlog < ApplicationRecord
  validates :content, length: { maximum: 14 },
                      presence: true
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :mini_blogs
  validates :name, presence: true
  validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hi
    render html: "hi everybody"
  end
  def secret
    render html: "sssh!"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/mini_blogs_controller.rb
class MiniBlogsController < ApplicationController
  before_action :set_mini_blog, only: [:show, :edit, :update, :destroy]

  # GET /mini_blogs
  # GET /mini_blogs.json
  def index
    @mini_blogs = MiniBlog.all
  end

  # GET /mini_blogs/1
  # GET /mini_blogs/1.json
  def show
  end

  # GET /mini_blogs/new
  def new
    @mini_blog = MiniBlog.new
  end

  # GET /mini_blogs/1/edit
  def edit
  end

  # POST /mini_blogs
  # POST /mini_blogs.json
  def create
    @mini_blog = MiniBlog.new(mini_blog_params)

    respond_to do |format|
      if @mini_blog.save
        format.html { redirect_to @mini_blog, notice: 'Mini blog was successfully created.' }
        format.json { render :show, status: :created, location: @mini_blog }
      else
        format.html { render :new }
        format.json { render json: @mini_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mini_blogs/1
  # PATCH/PUT /mini_blogs/1.json
  def update
    respond_to do |format|
      if @mini_blog.update(mini_blog_params)
        format.html { redirect_to @mini_blog, notice: 'Mini blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @mini_blog }
      else
        format.html { render :edit }
        format.json { render json: @mini_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mini_blogs/1
  # DELETE /mini_blogs/1.json
  def destroy
    @mini_blog.destroy
    respond_to do |format|
      format.html { redirect_to mini_blogs_url, notice: 'Mini blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mini_blog
      @mini_blog = MiniBlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mini_blog_params
      params.require(:mini_blog).permit(:title, :content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :bio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mini_blogs_helper.rb
module MiniBlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post %>
    <%= f.number_field :post %>
  </div>

  <div class="field">
    <%= f.label :user %>
    <%= f.number_field :user %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>User</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post %></td>
        <td><%= comment.user %></td>
        <td><%= comment.text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScaffoldTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mini_blogs/_form.html.erb
<%= form_for(mini_blog) do |f| %>
  <% if mini_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mini_blog.errors.count, "error") %> prohibited this mini_blog from being saved:</h2>

      <ul>
      <% mini_blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mini_blogs/edit.html.erb
<h1>Editing Mini Blog</h1>

<%= render 'form', mini_blog: @mini_blog %>

<%= link_to 'Show', @mini_blog %> |
<%= link_to 'Back', mini_blogs_path %>

app/views/mini_blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mini Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mini_blogs.each do |mini_blog| %>
      <tr>
        <td><%= mini_blog.title %></td>
        <td><%= mini_blog.content %></td>
        <td><%= mini_blog.user_id %></td>
        <td><%= link_to 'Show', mini_blog %></td>
        <td><%= link_to 'Edit', edit_mini_blog_path(mini_blog) %></td>
        <td><%= link_to 'Destroy', mini_blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mini Blog', new_mini_blog_path %>

app/views/mini_blogs/new.html.erb
<h1>New Mini Blog</h1>

<%= render 'form', mini_blog: @mini_blog %>

<%= link_to 'Back', mini_blogs_path %>

app/views/mini_blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @mini_blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @mini_blog.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @mini_blog.user_id %>
</p>

<%= link_to 'Edit', edit_mini_blog_path(@mini_blog) %> |
<%= link_to 'Back', mini_blogs_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_field :bio %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><b><%= user.name %></b></td>
        <td><%= user.email %></td>
        <td><i><%= user.bio %></i></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>FIRSTPOST!:</strong>
  [<%= if @user.mini_blogs.first then @user.mini_blogs.first.title end %>] - <%= if @user.mini_blogs.first then @user.mini_blogs.first.content end %>
</p>




<% @user.mini_blogs.each do |miniblog| %>
<p>
  <h3><%= miniblog.title %></h3>
  <p><%= miniblog.content %></p>
  <h4>Comments:</h4>

</p>
<% end %>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>